- src/App.css
- src/App.js
- src/components/Board.js
- src/components/Square.js
-Created 4 x 4 grid with clickable squares
> Setting up initial game board

- src/App.css
- src/components/Board.js
- src/components/Square.js
Removed X's and added additional state for background color change for each box that has been clicked.
> Added color change state

- src/App.css
- src/App.js
- src/components/Instructions.js
- src/components/PiecesContainer.js
- src/components/Square.js
All basic placeholders are there. Depending on the scope we may change up the instructions etc.
> Reformat page for the layout with instructions. 

- .gitignore
- package-lock.json
- package.json
- src/App.js
- src/components/Instructions.js
- src/components/Square.js
- src/firebaseConfig.js
- src/firebaseFunc.js
- src/reducers/boardReducer.js
- added dotenv module
- created .env file to host our keys
- added firebase functions
- converted App functional component to class component
> Firebase and dotenv setup

- src/App.js
- src/actions/actionTypes.js
- src/actions/index.js
- src/firebaseFunc.js
- src/reducers/boardReducer.js
- src/reducers/setShips.js
- Added initial save state function in App component
- Added reducer and action
- Creates a entry in the database on every refresh
> Firebase save state

- src/actions/actionTypes.js
- src/components/Board.js
- src/components/Square.js
- src/reducers/boardReducer.js
- Created 2 separate actions for player 1 and player 2 attack
- Changed state to stateCopy in boardreducer.js for the state name that was not changed
- Added actions to dispatch
- Need to figure out a way to dispatch these two actions after ships are set, or when set ships actions is disabled
> created two attack actions for multiplayer

- src/components/Board.js
- src/components/PiecesContainer.js
- src/reducers/boardReducer.js
-Players are only able to set one of each ship.
-Fixed bug for edge pieces
> Fixed functionality for horizontal pieces

- src/components/Square.js
- src/reducers/boardReducer.js
- Ship placement causes ship value to equal true
> ship state changes to true once piece is placed

- src/reducers/boardReducer.js
Ships can no longer be placed if hovered pieces are placed over existing ships on playing board
> ship placement no longer can overlap

- src/firebaseFunc.js
Nothing major, just cleaning up some console logs and setting variables for commonly used code
> Clean up Firebase functions

- src/components/StartModal.js
- src/firebaseFunc.js
Button to copy link onto clipboard is now working properly
> Copy game link to clipboard

- src/App.css
- src/App.js
- src/actions/actionTypes.js
- src/components/Board2.js
- src/components/Square.js
- src/reducers/boardReducer.js
- Implemented attack feature for opponents board
- Square turns grey when attacked and is empty
- Square turns red when ship is attacked
> Secondboard

- src/components/PiecesContainer.js
- src/reducers/boardReducer.js
- Game starts when player one sets all pieces
- Changes active state of player one to true
- Will have to add some changes once player two board is rendered to start game
when both players set all pieces
> Game Initiation

- src/App.js
- src/components/Board.js
- src/components/PiecesContainer.js
- src/components/Square.js
- src/reducers/boardReducer.js
Deleted most of the commented code and logs done by me. Left the ones that I wasn't sure if I should take out or not.
> Cleared out *most* logs

- package-lock.json
- package.json
- src/components/Chat.js
Some CSS may have to be updated for the div's to look correct....
> Added scrolling functionality for chat window.

- src/App.css
- src/App.js
- src/actions/actionTypes.js
- src/components/Board.js
- src/components/Board2.js
- src/components/P2PiecesContainer.js
- src/components/PlayerTwo.js
- src/components/PlayerTwoOpponent.js
- src/components/PlayerTwoOwn.js
- src/components/Square.js
- src/reducers/boardReducer.js
- Rendered player two board
- Piece orientation for player two
- Disabled pieces for player two after setting piece
- Hover bug fix
> Render p2 board

- src/App.js
- src/components/PiecesContainer.js
- Inner HTML of orientation button displays current orientation
> Orientation inner html

- src/App.css
- src/components/Chat.js
- Made instructions absolute positioned so that theyre not pushed to the right
-chat layout fixes
> Style fixes for layout

- src/components/PlayerTwo.js
Still more formatting needed but the chat has been added.
> Format p2 board to have chat functionality. 

- src/App.css
- src/App.js
- src/components/P1counter.js
- src/components/P2PiecesContainer.js
- src/components/PiecesContainer.js
- src/components/PlayerTwo.js
Container disappears once you place down all your pieces, and replaces it with the hit count.
> Ship container update for player one

- src/components/Board2.js
- src/components/Pieces.js
- src/components/PlayerTwoOpponent.js
- src/components/Square.js
- src/reducers/boardReducer.js
- Duplicate attacks prevented for each player on same square
> Duplicate Clicks

- src/App.css
- src/components/StartModal.js
- added link class
- blue color and larger font size
> add link class
